# Generated by Django 5.1.7 on 2025-04-08 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('industry_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('industry_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('year_of_study', models.IntegerField()),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('student_contact_number', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('town', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('plot_no', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('street', 'plot_no')},
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('plot_number', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.industry')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationPreference',
            fields=[
                ('pref_id', models.AutoField(primary_key=True, serialize=False)),
                ('pref_education_level', models.CharField(max_length=100)),
                ('positions_available', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='users.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='PreferredField',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_fields', to='users.organisationpreference')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPreference',
            fields=[
                ('student_pref_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pref_location', models.CharField(max_length=100)),
                ('available_from', models.DateField()),
                ('available_to', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredSkill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='users.organisationpreference')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.skill')),
            ],
            options={
                'unique_together': {('preference', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='PreferredIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.industry')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentpreference')),
            ],
            options={
                'unique_together': {('student', 'industry')},
            },
        ),
        migrations.CreateModel(
            name='DesiredSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.skill')),
                ('student_pref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentpreference')),
            ],
            options={
                'unique_together': {('student_pref', 'skill')},
            },
        ),
    ]
