# Generated by Django 5.1.7 on 2025-04-08 17:58

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logbook',
            fields=[
                ('logbook_id', models.CharField(default=users.models.generate_random_logbook_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('week_number', models.IntegerField()),
                ('log_entry', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organisation')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
