# Generated by Django 5.1.7 on 2025-04-13 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_studentmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('viewed', 'Viewed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='logbook',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmatch',
            name='organisation',
            field=models.ForeignKey(help_text='The organisation matched to the student', on_delete=django.db.models.deletion.CASCADE, to='users.organisation'),
        ),
        migrations.AlterField(
            model_name='studentmatch',
            name='student_preference',
            field=models.OneToOneField(help_text='The student preference that has been manually matched', on_delete=django.db.models.deletion.CASCADE, related_name='match', to='users.studentpreference'),
        ),
    ]
