# Generated by Django 5.1.7 on 2025-04-13 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_logbook_status_logbook_viewed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='week_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)]),
        ),
        migrations.AlterField(
            model_name='organisationpreference',
            name='positions_available',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_contact_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', message='Enter a valid phone number.')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Student ID must start with a year between 2015 and 2022 and be 9 digits long.', regex='^(201[5-9]|202[0-2])\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_study',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
