# Generated by Django 5.1.7 on 2025-04-13 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='week_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
