# Generated by Django 5.1.7 on 2025-04-13 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_student_year_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='contact_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\+?7\\d{6,14}$', message='Phone number must start with 7 and contain 7 to 15 digits.')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_contact_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\+?7\\d{6,14}$', message='Phone number must start with 7 and contain 7 to 15 digits.')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_study',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
