# Generated by Django 5.1.7 on 2025-04-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_organisation_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpreference',
            name='industries',
            field=models.ManyToManyField(blank=True, to='users.industry'),
        ),
        migrations.AddField(
            model_name='studentpreference',
            name='skills',
            field=models.ManyToManyField(blank=True, to='users.skill'),
        ),
    ]
